name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Install deps ğŸ›’
        run: |
          wget --no-verbose 'https://www.apache.org/dyn/closer.cgi?filename=/xmlgraphics/fop/binaries/fop-2.8-bin.tar.gz&action=download' -O fop-2.8-bin.tar.gz
          tar xfz fop-2.8-bin.tar.gz
          sudo apt-get update && sudo apt-get install xsltproc docbook-xml docbook-xsl docbook5-xml docbook-xsl-ns default-jre-headless texlive-latex-recommended texlive-latex-extra texlive-luatex latexmk fonts-texgyre fonts-lmodern gsfonts
          pip install sphinx jupyterlab nbconvert lxml plastex
      - name: Assemble sources ğŸ”§
        run: make assemble
      - name: LaTeX ğŸ”§
        run: make build-latex
      - name: DocBook ğŸ”§
        run: make FOP=../../fop-2.8/fop/fop build-docbook # FOP path is relative to build/docbook
      - name: Sphinx ğŸ”§
        run: make build-sphinx
      - name: Web ğŸ”§
        run: cp src/index.html build/index.html
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
